export default function Head() {
  return (
    <>
      <title>Gju upholders</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
<<<<<<< HEAD
  );
=======
  )
>>>>>>> ff4ff37 (Initial commit from Create Next App)
}
